import { For, Show } from "solid-js";
import styles from "./home.module.css";

export type HomeRoadcast = { slug: string; title: string; lastActivityAt?: Date | null };
export function HomeView(props: { roadcasts: HomeRoadcast[]; pending: boolean; error: string; onCreate: (title: string) => void }) {
  let titleInput!: HTMLInputElement;
  const submit = (event: SubmitEvent) => { event.preventDefault(); props.onCreate(titleInput.value); };
  return <main class={styles.page}><header class={styles.header}><a class={styles.brand} href="/" aria-label="Accueil Roadcast">roadcast</a><div><a href="/about">À propos</a><span class={styles.dot}>●</span><span>sans compte, par défaut</span></div></header><div class={styles.layout}><section class={styles.intro}><p class={styles.eyebrow}>VOTRE CONDUCTEUR, PARTOUT</p><h1>Préparez. Partagez.<br />Diffusez.</h1><p>Roadcast rassemble l’écriture, la lecture et la régie de vos chroniques. Chaque lien donne seulement l’accès nécessaire.</p><dl><div><dt>Écrire</dt><dd>Chroniques et médias dans le même espace.</dd></div><div><dt>Lire</dt><dd>Une version nette à envoyer à chaque chroniqueur.</dd></div><div><dt>Diffuser</dt><dd>Alpha, Bravo et Charly depuis la même préparation.</dd></div></dl></section><section class={styles.workspace} aria-labelledby="workspace-title"><div class={styles.tabs}><strong id="workspace-title">Mes roadcasts</strong><span>{props.roadcasts.length} récent{props.roadcasts.length > 1 ? "s" : ""}</span></div><form class={styles.create} onSubmit={submit}><label for="roadcast-title">Créer un roadcast</label><div><input ref={titleInput} id="roadcast-title" name="title" required minLength={3} maxLength={140} placeholder="Ex. émission du vendredi" autocomplete="off" /><button type="submit" disabled={props.pending}>{props.pending ? "Création…" : "Créer"}</button></div><Show when={props.error}><p class={styles.error} role="alert">{props.error}</p></Show></form><div class={styles.list}><Show when={props.roadcasts.length > 0} fallback={<p class={styles.empty}>Votre premier roadcast apparaîtra ici. Commencez simplement par son titre.</p>}><For each={props.roadcasts}>{(roadcast) => <a class={styles.roadcast} href={`/roadcast/${roadcast.slug}`}><span><strong>{roadcast.title}</strong><small>Dernière activité {roadcast.lastActivityAt ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium" }).format(roadcast.lastActivityAt) : "aujourd’hui"}</small></span><span aria-hidden="true">→</span></a>}</For></Show></div></section></div><footer class={styles.footer}><span>Roadcast v2 · mode concentration</span><span>Installez l’app pour garder vos chroniques à portée de main.</span></footer></main>;
}
