export * from "./ui"

export * as wsTest from "./ws-test.html?raw"
export * as header from "./header.html?raw"
export * as rupteur from "./rupteur.html?raw"
export * as footer from "./footer.html?raw"
export * as basicLayout from "./basic-layout.html?raw" 
export * as lastBroadcast from "./last-broadcast.html?raw"
export * as createBroadcastForm from "./create-broadcast-form.html?raw"
export * as errorMsg from "./error-msg.html?raw"
export * as broadcastLayout from "./broadcast-layout.html?raw"
export * as loader from "./loader.html?raw"